services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: fai-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - /opt/fai-storage:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  watchdog:
    image: willfarrell/autoheal:latest
    container_name: fai-watchdog
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ups-watchdog:
      image: python:3.9-slim
      container_name: ups-watchdog
      restart: always
      privileged: true 
      volumes:
        - ./scripts/ups_watchdog.py:/app/ups_watchdog.py:ro # 'ro'  ensures the container cannot modify your host script.
        - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket 
      devices:
        - "/dev/i2c-6:/dev/i2c-6" 
      # Automatically install the I2C library and DBUS tool before running the script
      command: >
        sh -c "apt-get update && apt-get install -y dbus && 
        pip install smbus2 && 
        python -u /app/ups_watchdog.py"

  mbusd:
      build: ./mbusd
      container_name: fai-mbusd
      restart: unless-stopped
      privileged: true
      volumes:
        - /dev:/dev  # The magic hot-plugging soft-mount
      environment:
        - RS485_PORT=/dev/serial/by-id/usb-WCH.CN_USB_Quad_Serial_BD65A1ABCD-if00     
      ports:
        - "5020:5020"
      healthcheck:
        test: ["CMD-SHELL", "netstat -ln | grep 5020 || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 15s


  nodered:
      build: ./nodered-build
      container_name: fai-nodered
      restart: unless-stopped
      privileged: true
      group_add:
        - "46"  # Critical: Grants Node-RED access to the USB radios
      volumes:
        - ./node-red-data:/data
        - /dev:/dev  # The magic hot-plugging soft-mount
        - /dev/serial:/dev/serial
      env_file:
        - .env  # This forces Docker to load the file
      environment:
        - NODE_RED_ENABLE_SAFE_MODE=false
        - TZ=UTC
        - GATEWAY_SERIAL=${GATEWAY_SERIAL}
        - GATEWAY_HOSTNAME=${GATEWAY_HOSTNAME}
        - POWER_METER_TYPE=${POWER_METER_TYPE}
      ports:
        - "1880:1880"
      depends_on:
        mqtt:
          condition: service_started
        mbusd:
          condition: service_started  # Loosened so Node-RED boots even if Modbus is unplugged!
      healthcheck:
        test: ["CMD-SHELL", "wget -q --spider http://localhost:1880/ || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
