version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: fai-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  nodered:
    image: nodered/node-red:latest
    container_name: fai-nodered
    restart: unless-stopped
    # 1. Map the Radiocrafts USB stick into the container
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      #- "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B401GJOW-if00-port0:/dev/ttyUSB0" 
    # 2. Permissions for serial port access (User:pi, Group:dialout)
    user: "1000:20" 
    # 3. Persistence
    volumes:
      - ./node-red-data:/data
    environment:
      - TZ=UTC
      # This pulls the variable from your .env file created by bootstrap.sh
      - GATEWAY_SERIAL=${GATEWAY_SERIAL}
      - GATEWAY_HOSTNAME=${GATEWAY_HOSTNAME}
    ports:
      - "1880:1880"
    depends_on:
      - mqtt