FROM nodered/node-red:latest

# Automatically install required community nodes during the build
RUN npm install node-red-dashboard \
                node-red-contrib-modbus \
                node-red-node-serialport
